name: Diff with BTFHub Archives
on:
  pull_request:

jobs:
  diff:
    name: Diff with BTFHub archive
    runs-on: ubuntu-20.04
    steps:
    - name: Check out code repo
      uses: actions/checkout@v2

    - name: Checkout public BTFHub repo
      uses: actions/checkout@v2
      with:
        repository: aquasecurity/btfhub-archive
        path: btfhub-archive-repo

    - name: Prepare current BTFHub repo archives
      run: make gather

    - name: Install packages required for BTF downloads
      run: |
        sudo add-apt-repository -y ppa:rafaeldtinoco/dwarves
        sudo apt-get update
        sudo apt-get install -y dwarves lynx sqlite3

    - name: Update BTF archives
      run: make update

    - name: Diff with BTFHub Archive
      run: |
        cd btfhub-archive-repo
        git status