name: PR

permissions: {}

on:
  workflow_dispatch: {}

  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - "**.sh"
      - "go.mod"
      - "go.sum"
      - "Makefile"
      - ".github/workflows/pr.yml"
      - ".github/actions/**"

concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  verify-and-test:
    name: Verify and Test
    runs-on: ubuntu-24.04
    permissions:
      contents: read # actions/checkout
    steps:
      #
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      #
      - name: Install Dependencies
        uses: ./.github/actions/build-dependencies
        with:
          from: pr
      #
      # CODE VERIFICATION
      #
      - name: Install staticchecker
        run: |
          GOROOT=/usr/local/go GOPATH=$HOME/go go install honnef.co/go/tools/cmd/staticcheck@ff63afafc529279f454e02f1d060210bd4263951 # v0.7.0 (2026.1)
          sudo cp $HOME/go/bin/staticcheck /usr/bin/
        shell: bash
      #
      - name: Install goimports-reviser
        run: |
          go install github.com/incu6us/goimports-reviser/v3@38044e6cb02749195e5384d9d9535ed00a10fc1f # v3.6.4
          sudo cp $HOME/go/bin/goimports-reviser /usr/bin/
        shell: bash
      #
      - name: Lint
        run: |
          if test -z "$(gofmt -l .)"; then
              echo "Congrats! There is nothing to fix."
          else
              echo "The following lines should be fixed."
              gofmt -s -d .
              exit 1
          fi
        shell: bash
      #
      - name: Check Golang Vet
        run: |
          make check-vet
        shell: bash
      #
      - name: Check with StaticCheck
        run: |
          make check-staticcheck
        shell: bash
      #
      # CODE TESTING
      #
      - name: Run Unit Tests
        run: |
          make test-unit
        shell: bash
