name: PR
permissions:
  contents: read
on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - "!docs/**"
      - "!archive/**"
      - "!custom-archive/**"
      - "!tools/bin/**"
      - "!**.yaml"
      - "!**.md"
      - "!**.txt"
      - "!**.conf"
      # override previous rules:
      - "**.c"
      - "**.h"
      - "**.go"
      - "**.sh"
      - ".github/workflows/pr.yml"
concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  verify-and-test:
    name: Verify and Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - name: Install Dependencies
        uses: ./.github/actions/build-dependencies
        with:
          from: pr
      - name: Install staticchecker
        shell: bash
        run: |
          set -euo pipefail
          GOROOT=/usr/local/go GOPATH="${HOME}/go" \
              go install honnef.co/go/tools/cmd/staticcheck@ff63afafc529279f454e02f1d060210bd4263951 # v2026.1
          sudo cp "${HOME}/go/bin/staticcheck" /usr/bin/
      - name: Install goimports-reviser
        shell: bash
        run: |
          set -euo pipefail
          GOROOT=/usr/local/go GOPATH="${HOME}/go" \
              go install github.com/incu6us/goimports-reviser/v3@fa5587e51ba33c58734984cb41370a5b2582d5b7 # v3.12.6
          sudo cp "${HOME}/go/bin/goimports-reviser" /usr/bin/
      - name: Lint
        shell: bash
        run: |
          set -euo pipefail
          if [[ -z "$(gofmt -l .)" ]]; then
              echo "Congrats! There is nothing to fix."
          else
              echo "The following lines should be fixed."
              gofmt -s -d .
              exit 1
          fi
      - name: Check Golang Vet
        shell: bash
        run: |
          set -euo pipefail
          make check-vet
      - name: Check with StaticCheck
        shell: bash
        run: |
          set -euo pipefail
          make check-staticcheck
      - name: Run Unit Tests
        shell: bash
        run: |
          set -euo pipefail
          make test-unit
