name: Run Tests
on:
  schedule:
    - cron: "0 1 * * 2"
  pull_request:
jobs:
  build:
    name: BATS Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Checkout public BTFHub repo
        uses: actions/checkout@v3
        with:
          repository: aquasecurity/btfhub-archive
          path: btfhub-archive-repo
      - name: Prepare current BTFHub repo archives
        run: make gather
      - name: Install packages required for BTF downloads
        run: |
          sudo add-apt-repository -y ppa:rafaeldtinoco/dwarves
          sudo apt-get update
          sudo apt-get install -y dwarves lynx
          sudo apt-get install -y rpm rpm2cpio
          sudo npm install -g bats
      - name: Run tests
        run: make test
